In [13]:
import numpy as np

a=np.array([[1,2,3],[7,8,9],[1,4,0]])
b=np.array([[4,5,6],[1,2,0],[7,5,8]])

print("matrix 1: ",a)
print(type(a))

print()

print("matrix 2:",b)
print(type(b))

print()

q=np.add(a,b)
print("Addition of two matrixes is:")
print(q)

print()

w=a-b
print("substraction of two matrixes is:",w)

print()

e=a/b
print("divide of two matrixes is:",e)

print()

r=a.dot(b)
print("multiplication of two matrixes is:",r)

print()

t=a*b
print("multiplication of two matrixes is:",t)
print("Transpose of a matrix:",a.T)
print("Transpose of a matrix:",b.T)

print()

print(np.mean(a))

print()

print(np.mean(a,axis=0))

print()

print(np.mean(a,axis=1))

print()

y=np.sort(a)

print()

y=np.sort(b)

print()

print(np.concatenate((a,b)))

print()

print(np.concatenate((b,a)))

print()

print(a.ndim)

print()

print(a.size)

print()

print(a.shape)

print()

print(a[::-1])

print()

print("rank of a:",np.linalg.matrix_rank(a))
print("rank of b:",np.linalg.matrix_rank(b))

print()

print("trace of a",np.trace(a))
print("trace of b",np.trace(b))

print()

print(a[1][2],b[1][2])

matrix 1:  [[1 2 3]
 [7 8 9]
 [1 4 0]]
<class 'numpy.ndarray'>

matrix 2: [[4 5 6]
 [1 2 0]
 [7 5 8]]
<class 'numpy.ndarray'>

Addition of two matrixes is:
[[ 5  7  9]
 [ 8 10  9]
 [ 8  9  8]]

substraction of two matrixes is: [[-3 -3 -3]
 [ 6  6  9]
 [-6 -1 -8]]

divide of two matrixes is: [[0.25       0.4        0.5       ]
 [7.         4.                inf]
 [0.14285714 0.8        0.        ]]

multiplication of two matrixes is: [[ 27  24  30]
 [ 99  96 114]
 [  8  13   6]]

multiplication of two matrixes is: [[ 4 10 18]
 [ 7 16  0]
 [ 7 20  0]]
Transpose of a matrix: [[1 7 1]
 [2 8 4]
 [3 9 0]]
Transpose of a matrix: [[4 1 7]
 [5 2 5]
 [6 0 8]]

3.888888888888889

[3.         4.66666667 4.        ]

[2.         8.         1.66666667]



[[1 2 3]
 [7 8 9]
 [1 4 0]
 [4 5 6]
 [1 2 0]
 [7 5 8]]

[[4 5 6]
 [1 2 0]
 [7 5 8]
 [1 2 3]
 [7 8 9]
 [1 4 0]]

2

9

(3, 3)

[[1 4 0]
 [7 8 9]
 [1 2 3]]

rank of a: 3
rank of b: 3

trace of a 9
trace of b 14

9 0


/var/folders/tf/fj21vfd13738_h422fhypm240000gp/T/ipykernel_21450/1468814549.py:27: RuntimeWarning: divide by zero encountered in true_divide
  e=a/b
