In [8]:
import numpy as np
#initialize arrays
A = np.array([2, 1, 5, 4])
B = np.array([3, 4, 7, 8])
C = np.array([8, 6, 0, 3])
#vertically stack arrays
output = np.vstack((A, B, C))
print(output)

print()

arr = np.array([x for x in range(11, 40)])
print("Original array")
print(arr)

print()


# using lambda to apply condition
new_arr = list(filter(lambda x: x > 15 and x % 2 == 0 and x % 10 != 0, arr))
# Converting new list into numpy array
new_arr = np.array(new_arr)
print()
print("New array")
print(new_arr)

a = np.array([1, 0, 3])
b = np.zeros((a.size, a.max()+1))
b[np.arange(a.size),a] = 1

print()
print(b)

[[2 1 5 4]
 [3 4 7 8]
 [8 6 0 3]]

Original array
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39]


New array
[16 18 22 24 26 28 32 34 36 38]

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
